# Javascript Node CircleCI 2.0 configuration file
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
version: 2
jobs:
  build:
    docker:
      - image: circleci/node:11.15
    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}

      - run:
          name: Install or update dependencies
          command: 'npm install'

      - run:
          name: Build the NPM package
          command: 'npm run build'

      - save_cache:
          key: dependency-cache-{{ checksum "package-lock.json" }}
          paths:
            - node_modules

      - persist_to_workspace:
          root: .
          paths:
            - .next

  deploy:
    docker:
      - image: circleci/node:11.15
    steps:
      - add_ssh_keys:
          fingerprints:
            - "ef:48:4c:ab:ba:a2:b9:58:cf:0c:3b:07:aa:e3:51:20"
      - attach_workspace:
          at: workspace

      - run:
          name: Deploy build tarball to Web server
          command: |
            echo "sdl.design ecdsa-sha2-nistp256 AAAAE2VjZHNhLXNoYTItbmlzdHAyNTYAAAAIbmlzdHAyNTYAAABBBDjUe/59wjwFP/2fSgMtFPyEUZhhVvepz/0kLf7WFNyxcr/iJalGvFaJJSPnLx8u2BdPV4XKCFwUm5yWNkim6Tw=" >> ~/.ssh/known_hosts
            scp -r workspace/.next $SSH_USER@$SSH_HOST:/var/www/web-portfolio/.next-new
      - run:
          name: SSH into Web server to apply the latest build
          command: |
            ssh $SSH_USER@$SSH_HOST "cd /var/www/web-portfolio && git fetch && git reset --hard ORIG_HEAD && npm install && rm .next -rf && mv .next-new .next && sudo systemctl restart web-portfolio"

workflows:
  version: 2
  build_deploy:
    jobs:
      - build
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
